### ISSUE TITLE
biber 2.14 crashes on osx 10.9

### ISSUE THREAD

**Issue by samcarter** [plk/biber#298]
Since the update to biber 2.14, it suddenly crashes with 

```
Can't load '/var/folders/z1/6807g5fn2tl27vlms0t5wqnm0000gq/T/par-7372616162/cache-487b97104ab64f45b54915cf8abf61a5c48774e9/b322188f.bundle' for module XML::LibXML: dlopen(/var/folders/z1/6807g5fn2tl27vlms0t5wqnm0000gq/T/par-7372616162/cache-487b97104ab64f45b54915cf8abf61a5c48774e9/b322188f.bundle, 1): Library not loaded: /opt/local/lib/libicui18n.58.dylib
  Referenced from: /var/folders/z1/6807g5fn2tl27vlms0t5wqnm0000gq/T//par-7372616162/cache-487b97104ab64f45b54915cf8abf61a5c48774e9/libxml2.2.dylib
  Reason: image not found at /loader/HASH(0x1008d2e18)/DynaLoader.pm line 197.
 at /loader/HASH(0x1009b3fb8)/PAR/Heavy.pm line 140.
BEGIN failed--compilation aborted at /var/folders/z1/6807g5fn2tl27vlms0t5wqnm0000gq/T/par-7372616162/cache-487b97104ab64f45b54915cf8abf61a5c48774e9/inc/lib/XML/LibXML.pm line 156.
Compilation failed in require at /var/folders/z1/6807g5fn2tl27vlms0t5wqnm0000gq/T/par-7372616162/cache-487b97104ab64f45b54915cf8abf61a5c48774e9/inc/lib/XML/LibXML/Simple.pm line 17.
BEGIN failed--compilation aborted at /var/folders/z1/6807g5fn2tl27vlms0t5wqnm0000gq/T/par-7372616162/cache-487b97104ab64f45b54915cf8abf61a5c48774e9/inc/lib/XML/LibXML/Simple.pm line 17.
Compilation failed in require at /var/folders/z1/6807g5fn2tl27vlms0t5wqnm0000gq/T/par-7372616162/cache-487b97104ab64f45b54915cf8abf61a5c48774e9/inc/lib/Biber/LaTeX/Recode.pm line 16.
BEGIN failed--compilation aborted at /var/folders/z1/6807g5fn2tl27vlms0t5wqnm0000gq/T/par-7372616162/cache-487b97104ab64f45b54915cf8abf61a5c48774e9/inc/lib/Biber/LaTeX/Recode.pm line 16.
Compilation failed in require at /var/folders/z1/6807g5fn2tl27vlms0t5wqnm0000gq/T/par-7372616162/cache-487b97104ab64f45b54915cf8abf61a5c48774e9/inc/lib/Biber/Utils.pm line 19.
BEGIN failed--compilation aborted at /var/folders/z1/6807g5fn2tl27vlms0t5wqnm0000gq/T/par-7372616162/cache-487b97104ab64f45b54915cf8abf61a5c48774e9/inc/lib/Biber/Utils.pm line 19.
Compilation failed in require at /var/folders/z1/6807g5fn2tl27vlms0t5wqnm0000gq/T/par-7372616162/cache-487b97104ab64f45b54915cf8abf61a5c48774e9/inc/lib/Biber/Internals.pm line 8.
BEGIN failed--compilation aborted at /var/folders/z1/6807g5fn2tl27vlms0t5wqnm0000gq/T/par-7372616162/cache-487b97104ab64f45b54915cf8abf61a5c48774e9/inc/lib/Biber/Internals.pm line 8.
Compilation failed in require at /loader/HASH(0x1009768e0)/parent.pm line 16.
BEGIN failed--compilation aborted at /var/folders/z1/6807g5fn2tl27vlms0t5wqnm0000gq/T/par-7372616162/cache-487b97104ab64f45b54915cf8abf61a5c48774e9/inc/lib/Biber.pm line 5.
Compilation failed in require at script/biber-darwin line 17.
BEGIN failed--compilation aborted at script/biber-darwin line 17.
```

The error message mentions `libicui18n.58.dylib`. Did anything change with this? I have icu4c/64.2 installed and it worked fine with biber 2.13.

Any ideas what I'm doing wrong?

**Comment by plk** [comment]
Did you try the legacy osx binary? This could be due to the OSX code signing changes which have to be made to the binary for TexLive compatibility.

**Comment by samcarter** [comment]
I'm using this binary `/usr/local/texlive/2019/bin/x86_64-darwinlegacy//biber`

**Comment by plk** [comment]
Hmm, are you sure nothing has changed on your end? The build server for the legacy binary hasn't changed as far as I know.

**Comment by samcarter** [comment]
After I noticed the problem, I copied the previous binary from last weeks backup and this works without problems (given that I also downgrade my biblatex version). So even if some things changed it was not a problem for the previous biber version

**Comment by plk** [comment]
I think you are right, I see some missing build lib links in the legacy build script for some reason. I will build a new dev 2.15 version and upload for you to test shortly.

**Comment by plk** [comment]
Please try the DEV 2.15 beta version for x86_64-darwinlegacy from SourceForge:

https://sourceforge.net/projects/biblatex-biber/files/biblatex-biber/development/binaries/OSX_Intel/

The links were missing for some libxml2 dependencies for the legacy binary build. You should be able to use the current v2.15 dev version with the current biblatex 3.14 release.

**Comment by samcarter** [comment]
You are my hero! v2.15 works great!

Thank you so much for still providing binaries for legacy systems!
