### ISSUE TITLE
`biber.universal-darwin` (79977, 2.22, 2026-08-13) crashes on macOS 26.6.1

### ISSUE THREAD

**Issue by HolgerGerhardt** [plk/biber#512]
After updating `biber.univeral-darwin` via TeX Live Utility to 79977 (2.22, 2026-08-13), it crashes on macOS 26.6.1.

Error message:

Can't load 

> '/var/folders/5r/jxdt6_xn4xg_yz_yyncc6pcc0000gp/T/par-6469656e73746c696368/cache-ef3dd1ed22f781987901e25bacfd01179fba172f/inc/lib/auto/Unicode/LineBreak/LineBreak.bundle' for module Unicode::LineBreak: dlopen(/var/folders/5r/jxdt6_xn4xg_yz_yyncc6pcc0000gp/T/par-6469656e73746c696368/cache-ef3dd1ed22f781987901e25bacfd01179fba172f/inc/lib/auto/Unicode/LineBreak/LineBreak.bundle, 0x0001): Library not loaded: /opt/homebrew/opt/libthai/lib/libthai.0.dylib Referenced from: <3012B9CE-F560-3F5A-B30D-2A829472CEEC> /private/var/folders/5r/jxdt6_xn4xg_yz_yyncc6pcc0000gp/T/par-6469656e73746c696368/cache-ef3dd1ed22f781987901e25bacfd01179fba172f/inc/lib/auto/Unicode/LineBreak/LineBreak.bundle Reason: tried: '/var/folders/5r/jxdt6_xn4xg_yz_yyncc6pcc0000gp/T//par-6469656e73746c696368/cache-ef3dd1ed22f781987901e25bacfd01179fba172f/libthai.0.dylib' (no such file), '/opt/homebrew/opt/libthai/lib/libthai.0.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/homebrew/opt/libthai/lib/libthai.0.dylib' (no such file), '/opt/homebrew/opt/libthai/lib/libthai.0.dylib' (no such file) at /loader/HASH(0x88ccbb690)/DynaLoader.pm line 210.  at /loader/HASH(0x88cd9f5d0)/PAR/Heavy.pm line 104. Compilation failed in require at /var/folders/5r/jxdt6_xn4xg_yz_yyncc6pcc0000gp/T/par-6469656e73746c696368/cache-ef3dd1ed22f781987901e25bacfd01179fba172f/inc/lib/Unicode/GCString.pm line 24. BEGIN failed--compilation aborted at /var/folders/5r/jxdt6_xn4xg_yz_yyncc6pcc0000gp/T/par-6469656e73746c696368/cache-ef3dd1ed22f781987901e25bacfd01179fba172f/inc/lib/Unicode/GCString.pm line 24. Compilation failed in require at /var/folders/5r/jxdt6_xn4xg_yz_yyncc6pcc0000gp/T/par-6469656e73746c696368/cache-ef3dd1ed22f781987901e25bacfd01179fba172f/inc/lib/Biber/Utils.pm line 32. BEGIN failed--compilation aborted at /var/folders/5r/jxdt6_xn4xg_yz_yyncc6pcc0000gp/T/par-6469656e73746c696368/cache-ef3dd1ed22f781987901e25bacfd01179fba172f/inc/lib/Biber/Utils.pm line 32. Compilation failed in require at /var/folders/5r/jxdt6_xn4xg_yz_yyncc6pcc0000gp/T/par-6469656e73746c696368/cache-ef3dd1ed22f781987901e25bacfd01179fba172f/inc/lib/Biber/Internals.pm line 8. BEGIN failed--compilation aborted at /var/folders/5r/jxdt6_xn4xg_yz_yyncc6pcc0000gp/T/par-6469656e73746c696368/cache-ef3dd1ed22f781987901e25bacfd01179fba172f/inc/lib/Biber/Internals.pm line 8. Compilation failed in require at /loader/HASH(0x88cd9d318)/parent.pm line 17. BEGIN failed--compilation aborted at /var/folders/5r/jxdt6_xn4xg_yz_yyncc6pcc0000gp/T/par-6469656e73746c696368/cache-ef3dd1ed22f781987901e25bacfd01179fba172f/inc/lib/Biber.pm line 5. Compilation failed in require at script/biber-darwin line 21. BEGIN failed--compilation aborted at script/biber-darwin line 21.
> 
> Process exited with error(s)

The previous version (75738, 2.21) works fine.

**Comment by plk** [comment]
Strange - I can't reproduce on 26.6.1 MacOS - works fine for me. Does it crash with just "biber --help"? Can you remove:

```
/var/folders/5r/jxdt6_xn4xg_yz_yyncc6pcc0000gp/T/par-6469656e73746c696368
```

and try it again?

**Comment by HolgerGerhardt** [comment]
Thank you for investigating this issue so quickly!

> Strange - I can't reproduce on 26.6.1 MacOS - works fine for me. Does it crash with just "biber --help"? Can you remove:
> 
> ```
> /var/folders/5r/jxdt6_xn4xg_yz_yyncc6pcc0000gp/T/par-6469656e73746c696368
> ```
> 
> and try it again?

Before opening this issue, I had removed that folder (multiple times). And yes, `biber` crashed also when executing `biber --help` and `biber --cache`.

I re-upgraded from 75738 to 79977 via TeX Live Utility a couple of minutes ago. It still crashed (also after removing that folder another time).

I have downgraded again to 75738, and everything works perfectly (without having to remove the folder in _/var_).

**Comment by plk** [comment]
Hmm, what about the universal binary from here:

https://sourceforge.net/projects/biblatex-biber/files/biblatex-biber/current/binaries/MacOS/

Should be the same - this one works fine for me.

**Comment by HolgerGerhardt** [comment]
I downloaded and extracted https://sourceforge.net/projects/biblatex-biber/files/biblatex-biber/current/binaries/MacOS/biber-darwin_universal.tar.gz/download. It generates the same error as above.

**Comment by HolgerGerhardt** [comment]
https://sourceforge.net/projects/biblatex-biber/files/biblatex-biber/current/binaries/MacOS/biber-darwin_x86_64.tar.gz/download, by contrast, works.

(I guess that is the version for Intel CPUs. I am testing this on an Apple Silicon machine with Rosetta 2 installed.)

**Comment by plk** [comment]
I think I know what the issue it, looking at it now.

**Comment by plk** [comment]
Can you try the universal binary from here again - it's been updated:

https://sourceforge.net/projects/biblatex-biber/files/biblatex-biber/current/binaries/MacOS/

**Comment by HolgerGerhardt** [comment]
> Can you try the universal binary from here again - it's been updated:
> 
> https://sourceforge.net/projects/biblatex-biber/files/biblatex-biber/current/binaries/MacOS/

I just did. Unfortunately, no success: Same issue as before (while 75738 works flawlessly).

**Comment by plk** [comment]
Different lib this time - I can reproduce, looking at it.

**Comment by plk** [comment]
Can you download it again now?

**Comment by HolgerGerhardt** [comment]
Success! The newest binary https://sourceforge.net/projects/biblatex-biber/files/biblatex-biber/current/binaries/MacOS/biber-darwin_universal.tar.gz/download works.

Thank you for your efforts!

**Comment by plk** [comment]
Good, will get this pushed to TL, thanks for confirming.

**Comment by HolgerGerhardt** [comment]
> Good, will get this pushed to TL, thanks for confirming.

What version/build number did you assign to the fix?

**Comment by plk** [comment]
Not done yet - still sorting this out with the TL maintainers

**Comment by plk** [comment]
CTAN is done so should appear in TL soon

**Comment by HolgerGerhardt** [comment]
I just installed version 80020 via TeX Live Utility, and it works.
