### ISSUE TITLE
isbn in @book causes biber to crash silently

### ISSUE THREAD

**Issue by crabmanX** [plk/biber#183]
biber fails to process my bib file as long as the isbn tag is present and fails silently. Once i remove the isbn, everything works fine. 

my setup:

openSUSE 42.3 + TeX Live 2016 from packages
texlive-biblatex  2016.122.3.4svn41192-23.4

```
$ biber --version
biber version: 2.5
```

```
$ pdflatex --version
pdfTeX 3.14159265-2.6-1.40.17 (TeX Live 2016/TeX Live for SUSE Linux)
```

i compile by running

```
$ pdflatex test.tex
[snip]
$ biber -D test
INFO - This is Biber 2.5
INFO - Logfile is 'test.blg'
INFO - DEBUG mode: all messages are logged to 'test.blg'
INFO - Reading 'test.bcf'
INFO - Found 1 citekeys in bib section 0
INFO - Processing section 0
INFO - Looking for bibtex format file 'literature.bib' for section 0
INFO - Decoding LaTeX character macros into UTF-8
INFO - Found BibTeX data source 'literature.bib'
$ echo $?
2
```

test.tex
```
\documentclass{scrbook}

\usepackage[backend=biber]{biblatex}
\addbibresource{literature.bib}

\begin{document}

Lorem ipsum \cite{Toro2009}.

\printbibliography

\end{document}
```

literature.bib
```
@book{Toro2009,
    author = {Toro, Eleuterio F.},
    edition = {3},
    isbn = {9783540252023},
    publisher = {Springer-Verlag},
    title = {{Riemann solvers and numerical methods for fluid dynamics}},
    url = {http://link.springer.com/content/pdf/10.1007/b79761.pdf},
    year = {2009}
}
```

test.blg
```
[0] Config.pm:343> INFO - This is Biber 2.5
[0] Config.pm:346> INFO - Logfile is 'test.blg'
[31] biber:295> INFO - === Fr Sep  8, 2017, 14:09:00
[46] Biber.pm:351> INFO - Reading 'test.bcf'
[103] Biber.pm:776> INFO - Found 1 citekeys in bib section 0
[103] Biber.pm:779> DEBUG - The citekeys for section 0 are: Toro2009
[110] Biber.pm:843> DEBUG - Adding sortlist of type 'entry' with sortscheme 'nty', sortnamekeyscheme 'global', labelprefix '' and name 'nty/global/' for section 0
[120] Biber.pm:3493> INFO - Processing section 0
[121] Biber.pm:3622> DEBUG - Looking for directly cited keys: Toro2009
[144] Biber.pm:3657> INFO - Looking for bibtex format file 'literature.bib' for section 0
[145] bibtex.pm:223> DEBUG - Caching data for BibTeX format file 'literature.bib' for section 0
[145] bibtex.pm:1187> INFO - Decoding LaTeX character macros into UTF-8
[145] bibtex.pm:1048> INFO - Found BibTeX data source 'literature.bib'
[146] bibtex.pm:1147> DEBUG - Cached Text::BibTeX entry for key 'Toro2009' from BibTeX file 'literature.bib'
[146] bibtex.pm:268> DEBUG - Text::BibTeX cache keys: Toro2009
[146] bibtex.pm:269> DEBUG - Wanted keys: Toro2009
[146] bibtex.pm:271> DEBUG - Looking for key 'Toro2009' in Text::BibTeX cache
[146] bibtex.pm:277> DEBUG - Found key 'Toro2009' in Text::BibTeX cache
[146] bibtex.pm:621> DEBUG - Source mapping (type=driver, key=Toro2009): Deleting field 'day'
[146] bibtex.pm:515> DEBUG - Source mapping (type=driver, key=Toro2009): Entry type is 'book' but map wants 'conference', skipping step ...
[147] bibtex.pm:515> DEBUG - Source mapping (type=driver, key=Toro2009): Entry type is 'book' but map wants 'electronic', skipping step ...
[147] bibtex.pm:515> DEBUG - Source mapping (type=driver, key=Toro2009): Entry type is 'book' but map wants 'www', skipping step ...
[147] bibtex.pm:510> DEBUG - Source mapping (type=driver, key=Toro2009): Entry type is 'book' but map wants 'mastersthesis' and step has 'final' set, skipping rest of map ...
[147] bibtex.pm:510> DEBUG - Source mapping (type=driver, key=Toro2009): Entry type is 'book' but map wants 'phdthesis' and step has 'final' set, skipping rest of map ...
[147] bibtex.pm:510> DEBUG - Source mapping (type=driver, key=Toro2009): Entry type is 'book' but map wants 'techreport' and step has 'final' set, skipping rest of map ...
[147] bibtex.pm:541> DEBUG - Source mapping (type=driver, key=Toro2009): No field 'hyphenation', skipping step ...
[147] bibtex.pm:541> DEBUG - Source mapping (type=driver, key=Toro2009): No field 'address', skipping step ...
[147] bibtex.pm:541> DEBUG - Source mapping (type=driver, key=Toro2009): No field 'school', skipping step ...
[147] bibtex.pm:541> DEBUG - Source mapping (type=driver, key=Toro2009): No field 'annote', skipping step ...
[147] bibtex.pm:541> DEBUG - Source mapping (type=driver, key=Toro2009): No field 'archiveprefix', skipping step ...
[147] bibtex.pm:541> DEBUG - Source mapping (type=driver, key=Toro2009): No field 'journal', skipping step ...
[147] bibtex.pm:541> DEBUG - Source mapping (type=driver, key=Toro2009): No field 'primaryclass', skipping step ...
[147] bibtex.pm:541> DEBUG - Source mapping (type=driver, key=Toro2009): No field 'key', skipping step ...
[147] bibtex.pm:541> DEBUG - Source mapping (type=driver, key=Toro2009): No field 'pdf', skipping step ...
[147] bibtex.pm:698> DEBUG - Creating biber Entry object with key 'Toro2009'
```

**Comment by plk** [comment]
I have no problems with biber 2.7 or 2.8 DEV - can you upgrade? 2.5 is a bit old.

**Comment by crabmanX** [comment]
unfortunately not. I am stuck with opensuse LEAP and they are stuck with texlive 2016

**Comment by bitstreamout** [comment]
It would be very nice to see a solution for this instead of simply closing this with a pointer forwarding to new biber 2.7

**Comment by plk** [comment]
Well, a fix means a fix to biber and so it means downloading a new version ... 2.8 is now released - have you tried this?

**Comment by bitstreamout** [comment]
Hmmm ... I'm maintainer of texlive and biber for opensuse and now an version update would require to break build dependcies, as well as product certificates.  Therefore a simple version update is a noop for an existing product. For openSUSE Tumbleweed currently  TeXLive 2017+biblatex-biber-2.7.tar.xz is in use and this had required a lot of update and new of perl packages/modules which now works.

A pointer to a git commit fixing the ISBN problem would be perfect for me as package maintainer.

**Comment by bitstreamout** [comment]
Just tried to reproduce this example and the other I've seen in bugzilla ... and both works with biber 2.5

**Comment by plk** [comment]
It will be tricky to find a commit for this because I couldn't reproduce it on 2.7 or 2.8. The requirements for 2.8 are not so different from 2.7 - just a couple of module upgrades - is that not possible for you?

**Comment by bitstreamout** [comment]
The full product/distribution has to (re)build with newer perl modules which will testes out by test build stages as well as by QA.  Normally I do this for a TeXLive version update within the project I'm using for TeXLive, then I add/update the perl modules required for biber as well as other packages required by other TeXLive sub packages.  After this build I submit this which leads to several test build stages to catch side effects like wrong or failing build of other packages.

**Comment by bitstreamout** [comment]
Here the test.blg as TXT file

[test.txt](https://github.com/plk/biber/files/1471225/test.txt)

**Comment by siko1056** [comment]
Just ran into this trouble as well, after reinstalling openSUSE Leap 42.3 on my machine.  Finally

    sudo zypper in perl-Business-ISBN

saved my day after digging 2 hours through perl scripts.



The issue was that a perl library `Business::ISBN` could not be loaded and caused biber 2.5 to die silently...  

https://github.com/plk/biber/blob/7435e66870309c1485abb9f42a6216addc4fc414/lib/Biber/Input/file/bibtex.pm#L925

@plk  I am no perl programmer, but isn't there a mechanism to crash more verbose in such cases for future releases?

@bitstreamout Could this package become a dependency in openSUSE for the biber package?

**Comment by crabmanX** [comment]
i can confirm that after installing perl-Business-ISBN, biber works as expected

@siko1056 you just made my day. I have about 20 openSUSE machines here, and biber was broken everywhere, until today. (Most people use bibtex anyway, but still)

**Comment by peschue** [comment]
Thank you for the nice comments. I found the reason for the crash only with strace. I second the question if biber could crash more verbosely in such cases in the future.
