### ISSUE TITLE
Can't get the latest macOS builds to work

### ISSUE THREAD

**Issue by dbmrq** [plk/biber#187]
When I try the version at [/current](https://sourceforge.net/projects/biblatex-biber/files/biblatex-biber/current/binaries/OSX_Intel/) I get:

```
~ > /Users/dbmrq/Downloads/biber --help
Attempt to reload DynaLoader.pm aborted.
Compilation failed in require at /loader/HASH(0x10089eb48)/XSLoader.pm line 121.
Compilation failed in require at /loader/HASH(0x1008cdb90)/IO/Handle.pm line 269.
BEGIN failed--compilation aborted at /loader/HASH(0x1008cdb90)/IO/Handle.pm line 269.
Compilation failed in require at /loader/HASH(0x1008cdc20)/IO/Seekable.pm line 101.
BEGIN failed--compilation aborted at /loader/HASH(0x1008cdc20)/IO/Seekable.pm line 101.
Compilation failed in require at /loader/HASH(0x1008cdb00)/IO/File.pm line 133.
BEGIN failed--compilation aborted at /loader/HASH(0x1008cdb00)/IO/File.pm line 133.
Compilation failed in require at -e line 162.
```

When I try the version at [/development](https://sourceforge.net/projects/biblatex-biber/files/biblatex-biber/development/binaries/OSX_Intel/) I get:

```
~ > /Users/dbmrq/Downloads/biber --help
Can't load '/var/folders/xk/81hr0f0n4hz_n1kwjp6lt70r0000gn/T/par-64626d7271/cache-82ce96a9b579ca7d831ec5498c59bb9c4087cc21/79628e8f.bundle' for module XML::LibXML: dlopen(/var/folders/xk/81hr0f0n4hz_n1kwjp6lt70r0000gn/T/par-64626d7271/cache-82ce96a9b579ca7d831ec5498c59bb9c4087cc21/79628e8f.bundle, 1): Library not loaded: /opt/local/lib/libxml2.2.dylib
  Referenced from: /var/folders/xk/81hr0f0n4hz_n1kwjp6lt70r0000gn/T//par-64626d7271/cache-82ce96a9b579ca7d831ec5498c59bb9c4087cc21/79628e8f.bundle
  Reason: Incompatible library version: 79628e8f.bundle requires version 12.0.0 or later, but libxml2.2.dylib provides version 10.0.0 at /loader/HASH(0x10188cc08)/DynaLoader.pm line 197.
 at /loader/HASH(0x10190b820)/PAR/Heavy.pm line 123.
BEGIN failed--compilation aborted at /var/folders/xk/81hr0f0n4hz_n1kwjp6lt70r0000gn/T/par-64626d7271/cache-82ce96a9b579ca7d831ec5498c59bb9c4087cc21/inc/lib/XML/LibXML.pm line 156.
Compilation failed in require at /var/folders/xk/81hr0f0n4hz_n1kwjp6lt70r0000gn/T/par-64626d7271/cache-82ce96a9b579ca7d831ec5498c59bb9c4087cc21/inc/lib/XML/LibXML/Simple.pm line 17.
BEGIN failed--compilation aborted at /var/folders/xk/81hr0f0n4hz_n1kwjp6lt70r0000gn/T/par-64626d7271/cache-82ce96a9b579ca7d831ec5498c59bb9c4087cc21/inc/lib/XML/LibXML/Simple.pm line 17.
Compilation failed in require at /var/folders/xk/81hr0f0n4hz_n1kwjp6lt70r0000gn/T/par-64626d7271/cache-82ce96a9b579ca7d831ec5498c59bb9c4087cc21/inc/lib/Biber/LaTeX/Recode.pm line 16.
BEGIN failed--compilation aborted at /var/folders/xk/81hr0f0n4hz_n1kwjp6lt70r0000gn/T/par-64626d7271/cache-82ce96a9b579ca7d831ec5498c59bb9c4087cc21/inc/lib/Biber/LaTeX/Recode.pm line 16.
Compilation failed in require at /var/folders/xk/81hr0f0n4hz_n1kwjp6lt70r0000gn/T/par-64626d7271/cache-82ce96a9b579ca7d831ec5498c59bb9c4087cc21/inc/lib/Biber/Utils.pm line 19.
BEGIN failed--compilation aborted at /var/folders/xk/81hr0f0n4hz_n1kwjp6lt70r0000gn/T/par-64626d7271/cache-82ce96a9b579ca7d831ec5498c59bb9c4087cc21/inc/lib/Biber/Utils.pm line 19.
Compilation failed in require at /var/folders/xk/81hr0f0n4hz_n1kwjp6lt70r0000gn/T/par-64626d7271/cache-82ce96a9b579ca7d831ec5498c59bb9c4087cc21/inc/lib/Biber/Internals.pm line 8.
BEGIN failed--compilation aborted at /var/folders/xk/81hr0f0n4hz_n1kwjp6lt70r0000gn/T/par-64626d7271/cache-82ce96a9b579ca7d831ec5498c59bb9c4087cc21/inc/lib/Biber/Internals.pm line 8.
Compilation failed in require at /loader/HASH(0x10188d748)/parent.pm line 16.
BEGIN failed--compilation aborted at /var/folders/xk/81hr0f0n4hz_n1kwjp6lt70r0000gn/T/par-64626d7271/cache-82ce96a9b579ca7d831ec5498c59bb9c4087cc21/inc/lib/Biber.pm line 5.
Compilation failed in require at script/biber-darwin line 17.
BEGIN failed--compilation aborted at script/biber-darwin line 17.
~ > 
```

Previous versions work fine. :/

**Comment by plk** [comment]
Which bitness? I think you might be trying the 32-bit version on a 64-bit platform.

**Comment by dbitouze** [comment]
Same kind of trouble with Linux build (on a 64-bit platform):

```bash
$ wget https://sourceforge.net/projects/biblatex-biber/files/biblatex-biber/current/binaries/Linux/biber-linux_x86_64.tar.gz
[...]
$ tar xvfz biber-linux_x86_64.tar.gz
biber
$ biber -v                          
Attempt to reload DynaLoader.pm aborted.
Compilation failed in require at /loader/HASH(0x2439060)/XSLoader.pm line 118.
Compilation failed in require at /loader/HASH(0x250c488)/IO/Handle.pm line 269.
BEGIN failed--compilation aborted at /loader/HASH(0x250c488)/IO/Handle.pm line 269.
Compilation failed in require at /loader/HASH(0x250c518)/IO/Seekable.pm line 101.
BEGIN failed--compilation aborted at /loader/HASH(0x250c518)/IO/Seekable.pm line 101.
Compilation failed in require at /loader/HASH(0x250c3f8)/IO/File.pm line 133.
BEGIN failed--compilation aborted at /loader/HASH(0x250c3f8)/IO/File.pm line 133.
Compilation failed in require at -e line 162.
```

**Comment by plk** [comment]
This is very strange, I just downloaded exactly what you did using the same commands and it is fine for me. Which linux are you using? My build servers are 10.10.

**Comment by dbitouze** [comment]
I'm using Linux Mageia 6.

>My build servers are 10.10.

I'm not sure what you mean by this.

Anyway, just like dbmrq, the previous versions used to work like a charm (if I remember well, the previous one which worked was downloaded 3 days ago).

**Comment by plk** [comment]
Sorry, I meant Ubuntu.10.10. I try to build on an older distribution for maximum compat. Just to be sure, you are using the 64-bit version on 64-bit OS?

**Comment by dbitouze** [comment]
>Sorry, I meant Ubuntu.10.10.

No problem. Linux Mageia is a `.rpm` flavor Linux distribution (just as Red Hat or Fedora), not a `.deb` flavor one (like Debian or Ubuntu).

> Just to be sure, you are using the 64-bit version on 64-bit OS?

Yes.

**Comment by plk** [comment]
Can you paste the output of `ldd biber` here?

**Comment by dbitouze** [comment]
```
$ ldd ./biber
        linux-vdso.so.1 (0x00007fff0ad92000)
        libpthread.so.0 => /lib64/libpthread.so.0 (0x00007fb1fdcc1000)
        libnsl.so.1 => /lib64/libnsl.so.1 (0x00007fb1fdaa8000)
        libdl.so.2 => /lib64/libdl.so.2 (0x00007fb1fd8a4000)
        libm.so.6 => /lib64/libm.so.6 (0x00007fb1fd5a4000)
        libcrypt.so.1 => /lib64/libcrypt.so.1 (0x00007fb1fd356000)
        libutil.so.1 => /lib64/libutil.so.1 (0x00007fb1fd153000)
        libc.so.6 => /lib64/libc.so.6 (0x00007fb1fcda0000)
        /lib64/ld-linux-x86-64.so.2 (0x00007fb1fdede000)
```

**Comment by plk** [comment]
I just installed a fresh Mageia 6 virtualbox vm and downloaded the bib linux 64-bit 2.8 version from Sourceforge and it works fine for me - `biber -v` returns the version number as usual.

**Comment by dbmrq** [comment]
I'm trying the 64 bit binaries in a 64 bit mac (using macOS High Sierra), but I also tried the 32 bit build just to be sure and the results are the same. The 64 bit build of version 2.7 works, on the other hand. This is the output of `otool -L`:

```
~ > otool -L /Users/dbmrq/Downloads/biber
/Users/dbmrq/Downloads/biber:
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 125.2.10)
	/usr/lib/libutil.dylib (compatibility version 1.0.0, current version 1.0.0)
```

**Comment by dbitouze** [comment]
Well, very puzzling! But I'm not the only one facing this problem...

**Comment by dbitouze** [comment]
Interestingly enough, the 32-bit version of `biber` works as expected on my 64-bit Linux box.

**Comment by plk** [comment]
Weird. Can you check with `file` the actual bitness of `biber` is correct as labelled?

**Comment by dbitouze** [comment]
>Can you check with `file` the actual bitness of `biber` is correct as labelled?

@plk If this is for me, I don't understand what you mean.

**Comment by plk** [comment]
I mean run `file biber` and see what is returned.

**Comment by dbitouze** [comment]
- [ 32 bit version:] 
```bash
$ file biber
biber: ELF 32-bit LSB executable, Intel 80386, version 1 (SYSV), dynamically linked, interpreter /lib/ld-linux.so.2, for GNU/Linux 2.6.15, BuildID[sha1]=b10f6bbbae72bd9d81188eca2f9fdd9f5a1550c0, stripped
```
- [ 64 bit version:] 
```bash
$ file biber
biber: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 2.6.15, BuildID[sha1]=9f41ca39557c67d096f2512299f1986b35848cff, stripped
```

**Comment by plk** [comment]
Hmm, all looks fine.

**Comment by dbitouze** [comment]
But, for the 64 bit version, still:
```bash
$ biber -v
Attempt to reload DynaLoader.pm aborted.
Compilation failed in require at /loader/HASH(0x1898070)/XSLoader.pm line 118.
Compilation failed in require at /loader/HASH(0x196b498)/IO/Handle.pm line 269.
BEGIN failed--compilation aborted at /loader/HASH(0x196b498)/IO/Handle.pm line 269.
Compilation failed in require at /loader/HASH(0x196b528)/IO/Seekable.pm line 101.
BEGIN failed--compilation aborted at /loader/HASH(0x196b528)/IO/Seekable.pm line 101.
Compilation failed in require at /loader/HASH(0x196b408)/IO/File.pm line 133.
BEGIN failed--compilation aborted at /loader/HASH(0x196b408)/IO/File.pm line 133.
Compilation failed in require at -e line 162.
```

**Comment by plk** [comment]
The one here:

https://www.dropbox.com/s/f5l2dq8a4uh7sz5/biber?dl=0

works fine on my Ubuntu 10.10 and Mageia 6 64-bit VMs. Can you try it?

**Comment by plk** [comment]
@dbmrq - I will try to rebuild and upload again later - I can't reproduce this currently - if I download from SF and run on my 10.13.1 OSX machine.

**Comment by dbitouze** [comment]
Works fine:
```bash
$ biber -v                               
biber version: 2.7
```

**Comment by plk** [comment]
@dbitouze - are you sure you are calling the right one? It should return version 2.8.

**Comment by dbitouze** [comment]
>are you sure you are calling the right one? It should return version 2.8.

Sorry, I forgot to run `chmod u+x biber`. So, unfortunately, it doesn't work:

```
$ md5sum ./biber                                                 
8557dc229734e519a44bb11621ecc8ed  biber
$ ./biber -v     
Attempt to reload DynaLoader.pm aborted.
Compilation failed in require at /loader/HASH(0x2681070)/XSLoader.pm line 118.
Compilation failed in require at /loader/HASH(0x2754498)/IO/Handle.pm line 269.
BEGIN failed--compilation aborted at /loader/HASH(0x2754498)/IO/Handle.pm line 269.
Compilation failed in require at /loader/HASH(0x2754528)/IO/Seekable.pm line 101.
BEGIN failed--compilation aborted at /loader/HASH(0x2754528)/IO/Seekable.pm line 101.
Compilation failed in require at /loader/HASH(0x2754408)/IO/File.pm line 133.
BEGIN failed--compilation aborted at /loader/HASH(0x2754408)/IO/File.pm line 133.
Compilation failed in require at -e line 162.
```

**Comment by stwagnr** [comment]
I would like to highlight that, by default, there is no file `/opt/local/lib/libxml2.2.dylib` in macOS 10.13.1 as far as I can tell. That is why I get the same error message as @dbmrq (which is particularly problematic since the TeX Live Utility included in MacTeX already distributes `biblatex 3.8`, which seems to require `biber 2.8`).

The problem might be connected to `dist/darwin_x86_64/build.sh`, which specifies the library mentioned above, but not really sure.

**Comment by stwagnr** [comment]
Quick followup:
The library exists, of course, in the following location:
```
user@machine:~ > find /usr/lib -iname "libxml2.2.dylib"
/usr/lib/libxml2.2.dylib
```

**Comment by plk** [comment]
This lib shouldn’t even need to exist on the machine as it’s packed with biber.

**Comment by plk** [comment]
Can you try this again? I have updated libxml2 on my OSX 64-bit build server, rebuilt XML::LibXML and re-packed biber. Just pull it from SourceForge in about an hour to allow some replication time

**Comment by dbmrq** [comment]
A new version already showed up here for me (at least the site says it's from 10 minutes ago), but I still get that second error on both the 32 and 64 bit versions:

```
Can't load '/var/folders/xk/81hr0f0n4hz_n1kwjp6lt70r0000gn/T/par-64626d7271/cache-99866aded8e2c9e6afeefe400744441b75961bd9/79628e8f.bundle' for module XML::LibXML: dlopen(/var/folders/xk/81hr0f0n4hz_n1kwjp6lt70r0000gn/T/par-64626d7271/cache-99866aded8e2c9e6afeefe400744441b75961bd9/79628e8f.bundle, 1): Library not loaded: /opt/local/lib/libxml2.2.dylib
  Referenced from: /var/folders/xk/81hr0f0n4hz_n1kwjp6lt70r0000gn/T//par-64626d7271/cache-99866aded8e2c9e6afeefe400744441b75961bd9/79628e8f.bundle
  Reason: Incompatible library version: 79628e8f.bundle requires version 12.0.0 or later, but libxml2.2.dylib provides version 10.0.0 at /loader/HASH(0x100914020)/DynaLoader.pm line 197.
 at /loader/HASH(0x10100ec38)/PAR/Heavy.pm line 123.
BEGIN failed--compilation aborted at /var/folders/xk/81hr0f0n4hz_n1kwjp6lt70r0000gn/T/par-64626d7271/cache-99866aded8e2c9e6afeefe400744441b75961bd9/inc/lib/XML/LibXML.pm line 156.
Compilation failed in require at /var/folders/xk/81hr0f0n4hz_n1kwjp6lt70r0000gn/T/par-64626d7271/cache-99866aded8e2c9e6afeefe400744441b75961bd9/inc/lib/XML/LibXML/Simple.pm line 17.
BEGIN failed--compilation aborted at /var/folders/xk/81hr0f0n4hz_n1kwjp6lt70r0000gn/T/par-64626d7271/cache-99866aded8e2c9e6afeefe400744441b75961bd9/inc/lib/XML/LibXML/Simple.pm line 17.
Compilation failed in require at /var/folders/xk/81hr0f0n4hz_n1kwjp6lt70r0000gn/T/par-64626d7271/cache-99866aded8e2c9e6afeefe400744441b75961bd9/inc/lib/Biber/LaTeX/Recode.pm line 16.
BEGIN failed--compilation aborted at /var/folders/xk/81hr0f0n4hz_n1kwjp6lt70r0000gn/T/par-64626d7271/cache-99866aded8e2c9e6afeefe400744441b75961bd9/inc/lib/Biber/LaTeX/Recode.pm line 16.
Compilation failed in require at /var/folders/xk/81hr0f0n4hz_n1kwjp6lt70r0000gn/T/par-64626d7271/cache-99866aded8e2c9e6afeefe400744441b75961bd9/inc/lib/Biber/Utils.pm line 19.
BEGIN failed--compilation aborted at /var/folders/xk/81hr0f0n4hz_n1kwjp6lt70r0000gn/T/par-64626d7271/cache-99866aded8e2c9e6afeefe400744441b75961bd9/inc/lib/Biber/Utils.pm line 19.
Compilation failed in require at /var/folders/xk/81hr0f0n4hz_n1kwjp6lt70r0000gn/T/par-64626d7271/cache-99866aded8e2c9e6afeefe400744441b75961bd9/inc/lib/Biber/Internals.pm line 8.
BEGIN failed--compilation aborted at /var/folders/xk/81hr0f0n4hz_n1kwjp6lt70r0000gn/T/par-64626d7271/cache-99866aded8e2c9e6afeefe400744441b75961bd9/inc/lib/Biber/Internals.pm line 8.
Compilation failed in require at /loader/HASH(0x100914b60)/parent.pm line 16.
BEGIN failed--compilation aborted at /var/folders/xk/81hr0f0n4hz_n1kwjp6lt70r0000gn/T/par-64626d7271/cache-99866aded8e2c9e6afeefe400744441b75961bd9/inc/lib/Biber.pm line 5.
Compilation failed in require at script/biber-darwin line 17.
BEGIN failed--compilation aborted at script/biber-darwin line 17.
```

😢

Very weird that you can't reproduce it. Is it possible that the wrong version of libxml2 is getting bundled somehow, even if you have the right version on your system?

**Comment by stwagnr** [comment]
Same error messages here.

**Comment by dbmrq** [comment]
Also I just saw someone else with the same problem here: https://tex.stackexchange.com/q/399831/102699

**Comment by plk** [comment]
I can reproduce now if I rename the /opt/local/lib/libml2.2.dylib on my machine. This may be a PAR::Packer problem as it seems not to be finding the packed libxml2 for some reason.

**Comment by stwagnr** [comment]
Maybe this helps: I linked version 2.9.7 of `libxml2.2.dylib` (from Homebrew) into `/opt/local/lib` and the error messages now says:

```
Can't load '/var/folders/xx/h56tdp5962x89fds2mx9hc0w0000gn/T/par-7761676e6572/cache-284893d39de4293722d6902cdc883227c86ae2be/35543de4.bundle' for module XML::LibXML: dlopen(/var/folders/xx/h56tdp5962x89fds2mx9hc0w0000gn/T/par-7761676e6572/cache-284893d39de4293722d6902cdc883227c86ae2be/35543de4.bundle, 1): Library not loaded: /opt/local/lib/libiconv.2.dylib
  Referenced from: /var/folders/xx/h56tdp5962x89fds2mx9hc0w0000gn/T//par-7761676e6572/cache-284893d39de4293722d6902cdc883227c86ae2be/35543de4.bundle
  Reason: Incompatible library version: 35543de4.bundle requires version 9.0.0 or later, but libiconv.2.dylib provides version 7.0.0 at /loader/HASH(0x1018586b0)/DynaLoader.pm line 197.
 at /loader/HASH(0x1018f1ec8)/PAR/Heavy.pm line 123.
[...]
```

**Comment by dbmrq** [comment]
So libxml2 isn't the only library not bundled properly… there's at least libiconv too, but something else would probably show up if we linked that one as well.

So it does look like a problem with the packer. And it wasn't happening with version 2.7. Maybe using an older version of PAR::Packer could work?

**Comment by plk** [comment]
That's rarely a good idea. I am currently updating my build OSX VM.

**Comment by dbitouze** [comment]
>Can you try this again? I have updated libxml2 on my OSX 64-bit build server, rebuilt XML::LibXML and re-packed biber. Just pull it from SourceForge in about an hour to allow some replication time

This one (from `biber-linux_x86_64.tar.gz`):
```bash
$ md5sum ./biber                                       
9af21dc10092321c5bc8187149daaf2d  ./biber
$ ./biber -v          
biber version: 2.8
```
 works like a charm on my Linux 64 bits box.

**Comment by plk** [comment]
Ok, then I think the linux issue is fixed. OSX is still a problem.

**Comment by moewew** [comment]
It seems that TeX live are reverting back to 3.7 for the time being (see http://tug.org/pipermail/tex-live/2017-November/040777.html and http://tug.org/pipermail/tex-live/2017-November/040779.html). Should we ask MikTeX to do the same?

**Comment by plk** [comment]
Yes, there are some very low-level issues with PAR::Packer and OSX. I have them fixed on Linux but it is not clear what is happening on OSX. Am in discussion with the PAR::Packer author.

**Comment by moewew** [comment]
Do you want me to ask the MikTeX maintainer at https://github.com/MiKTeX/miktex-packaging/issues, or would you rather discuss it with him himself?

**Comment by plk** [comment]
Can you do it? I am deep in the guts of library path with the PAR::Packer author. Something has changed in the way macports delivers/compiles shlibs it seems.

**Comment by moewew** [comment]
On to it.

**Comment by plk** [comment]
I have confirmed with the PAR::Packer maintainer that this is a bug in the packer module (possibly caused by recent macport compilation flags for some library updates). We have tested a fix which solves the issue and expect to release shortly.

**Comment by plk** [comment]
Please get 2.8 again from SF, I believe that this is now resolved.

**Comment by dbmrq** [comment]
It works! 🍾 

Thank you for your work on this!

**Comment by moewew** [comment]
Are there still some issues left or can we expect Biber to reach CTAN soon?

**Comment by plk** [comment]
@moewew - Should be there today I think - I just provided a re-packed dist to CTAN people who are happy now and we agreed on how this will be handled in future.

**Comment by moewew** [comment]
Brilliant!
